[project]
name = "stacks-timelock"
description = "Time-locked transactions and vesting on Stacks"
authors = ["serayd61"]
telemetry = false
cache_dir = ".cache"
requirements = []

[contracts.timelock]
path = "contracts/timelock.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

